server:
  port: 8080

spring:
  application:
    name: projetoUM

  datasource:
    url: jdbc:h2:mem:accdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

